<a href="https://colab.research.google.com/github/tejask-42/Modelling-Gravitational-Systems/blob/main/Week_1/Python_basics_Assignment_KCAP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a short assignment on basics on torch. Before you start make sure that you are using the T4 GPU as runtime on google colab. Also note that, the free version of google colab only allows one GPU runtime per account at a given time.

General principles: (for freshies)

* For any piece of software that you use, you are NOT expected to remember all the details of the software. For example, if you use python, you may remember the syntax for very frequently used features such as loops/conditionals etc but you won't be expected to remember the syntax of scipy's curve fit module.
* If you do not no the syntax of any task, first step is to search for it on stackoverflow (directly do a google search, you will get some stackoverflow etc search results). If the results are not satisfactory, try using chatGPT or google bard (Caution: the AI search tools tend to hallucinate and create their own answers for some prompts).
* You can also go through the documentation of the module/library/software to find the functionality that you need.

Here are links to documentation of some useful python libraries:
* [numpy](https://numpy.org/doc/stable/)
* [matplotlib](https://matplotlib.org/stable/index.html)
* [pytorch](https://pytorch.org/docs/stable/index.html)
* [pandas](https://pandas.pydata.org/docs/)

In [ ]:
!pip install torch
!pip install matplotlib
!pip install numpy
!pip install pandas
!pip install ipympl

In [ ]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

You can check the specs of GPU alloted to you using the nvidia-smi command. Mind, you this command works only on devices with NVIDIA CUDA support. Since colab uses CUDA, this command works.

In [ ]:
!nvidia-smi

Tue Dec 10 14:25:18 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

As torch is a ML library it supports GPU computation. But numpy does NOT. For torch to use a GPU for computation, you must set the device to 'cuda'.

In [ ]:
device = 'cuda'

A tensor for our purposes is just a multi-dimensional array. For example, a vector is a 1D tensor and a matrix is a 2D tensor.

In [ ]:
# numpy tensor/ndarray
array = np.array([[1,2,3,4],[5,6,7,8]])
print(array)
print('type :', type(array))
print('shape :', array.shape)

[[1 2 3 4]
 [5 6 7 8]]
type : <class 'numpy.ndarray'>
shape : (2, 4)


In [ ]:
# torch tensor
tensor = torch.tensor([[1,2,3,4],[5,6,7,8]], device = device)
print(tensor)
print('type :', type(tensor))
print('shape :', tensor.shape)
print('device :', tensor.device)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]], device='cuda:0')
type : <class 'torch.Tensor'>
shape : torch.Size([2, 4])
device : cuda:0


Binary operations cannot be used on torch.tensors which are stores on different devices.

In [ ]:
# this gives an error
A = torch.tensor([[1,2,3,4],[5,6,7,8]], device = 'cuda')
B = torch.tensor([[1,2,3,4],[5,6,7,8]], device = 'cuda')
C = A + B
print(C)

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16]], device='cuda:0')


Correct the code in the above cell. The array C should be on 'cuda'.

In [ ]:
# C =
print(C)

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16]], device='cuda:0')


Why is it that people use libraries like numpy and torch? You could always write equivalent python code and work with it. Right? Obviously, the answer is....

In [ ]:
l_python = [i for i in range(10000)]
l_numpy = np.array(l_python)

import time

In [ ]:
t0 = time.time()
for i in range(10):
  for j,element in enumerate(l_python):
    l_python[j] = element*element
t = time.time()
print('python :', t - t0)

python : 0.26359128952026367


In [ ]:
t0 = time.time()
for i in range(10):
  l_numpy = l_numpy*l_numpy
t = time.time()
print('numpy :', t - t0)

numpy : 0.00044655799865722656


See the difference! The main reason for this difference is that numpy doesn't simply use the regular python functionalities, it uses a C backend. I won't elaborate on this (because I haven't researched on this enough). Basically in libraries like numpy python is just an interface between the programmer and the actual backend. This is a trend that is followed in various domains of computer science, python is used as an interface between programmer and backend because python is easy to use.

In [ ]:
t0 = time.time()
for i in range(10):
  for j,element in enumerate(l_numpy):
    l_numpy[j] = element*element
t = time.time()
print('numpy with loops :', t - t0)

numpy with loops : 0.06724023818969727


<ipython-input-96-83e9c26a2191>:4: RuntimeWarning: overflow encountered in scalar multiply
  l_numpy[j] = element*element


What is this? Using for loops with a numpy array leads to a very significant slowdown. This is because of the way numpy is implemented. Numpy and torch are made for vectorized operations. To put simply, for/while loops are banned!

A lot of the regular coding (using loops) that we do with arrays has an equivalent vectorized version. Lets see some of that.

Task 1:

Create a 4D numpy array with (4,2,5,6) indices in the four dimensions. All the elements of the array must be 1s. Also create a similar torch tensor.

In [ ]:
np_ones = np.ones((4, 2, 5, 6))
print(np_ones.shape)

torch_ones = torch.ones((4, 2, 5, 6), device = device)
print(torch_ones.shape)

(4, 2, 5, 6)
torch.Size([4, 2, 5, 6])


Task 2:

Vectorize the following code

In [ ]:
# vectorize this:
l = [1 for i in range(20)]
for i, element in enumerate(l):
  l[i] = element + 10
# end

l

[11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11]

In [ ]:
func = np.vectorize(lambda x: int(x + 10))
l = func(np.ones(20))
l

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11])

Task 3:

Vectorize the following code

In [ ]:
np.random.seed(0)
N = [i for i in range(10)]
A = np.random.choice(N, size = (10,5))
B = np.random.choice(N, size = (5))
C = np.random.choice(N, size = (10))

# vectorize this
for j in range(10):
  for i in range(5):
    A[j][i] += B[i]
for i in range(5):
  for j in range(10):
    A[j][i] += C[j]
# end

A

array([[13, 12, 16, 16, 21],
       [13, 11, 14, 11, 14],
       [ 8, 11, 14, 14,  8],
       [10, 15, 16, 17, 11],
       [14, 22, 22, 23, 19],
       [11, 12, 16, 18, 14],
       [ 3,  8, 14,  7, 10],
       [ 4,  8, 13,  6,  8],
       [16, 20, 12, 16, 20],
       [12, 15, 21, 16, 15]])

In [ ]:
np.random.seed(0)
N = np.arange(0, 10)
A = np.random.choice(N, size = (10,5))
B = np.random.choice(N, size = (5))
C = np.random.choice(N, size = (10))


A = A + C[:, np.newaxis] # broadcasting C to each row
A = A + B[np.newaxis, :] # broadcasting B to each column

A

array([[13, 12, 16, 16, 21],
       [13, 11, 14, 11, 14],
       [ 8, 11, 14, 14,  8],
       [10, 15, 16, 17, 11],
       [14, 22, 22, 23, 19],
       [11, 12, 16, 18, 14],
       [ 3,  8, 14,  7, 10],
       [ 4,  8, 13,  6,  8],
       [16, 20, 12, 16, 20],
       [12, 15, 21, 16, 15]])

Task 4:

Reshape the following arrays to the sizes mentioned and observe the results.

In [ ]:
# 4

# (10,5) to (2,5,5)
A1 = np.random.choice(N, size = (2,5,5))

# (2,3) to (6,)
A2 = np.random.choice(N, size = (6,))

# Get the transpose
A3 = np.random.choice(N, size = (4, 3))
A1, A2, A3

(array([[[9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1]],
 
        [[5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]]]),
 array([2, 3, 4, 1, 2, 9]),
 array([[1, 4, 6],
        [8, 2, 3],
        [0, 0, 6],
        [0, 6, 3]]))

Task 5:

Using numpy or torch library functions, get an identity matrix of size 10.

In [ ]:
mat_one = np.eye(10, 10)
mat_one

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Task 6:

You are given a matrix $A$ of shape (4,5), you want the second half (to be precise, rows 2,3 (with 0 indexing)) of the matrix. Slice the matrix!

In [ ]:
A = np.random.choice(N, size = (4,5))
A

array([[3, 8, 8, 8, 2],
       [3, 2, 0, 8, 8],
       [3, 8, 2, 8, 4],
       [3, 0, 4, 3, 6]])

In [ ]:
A[2:, :]

array([[3, 8, 2, 8, 4],
       [3, 0, 4, 3, 6]])

Task 7:

You are given a matrix $A$ of size (4,3). Sum up all the rows of the matrix and store it in $R$. Take average of all the columns of $A$ and store it in $C$. Note that $R$ should be a row matrix and $C$ a column matrix, that is shapes must be (1,3) and (4,1) respectively.

In [ ]:
np.random.seed(0)
A = np.random.choice(N, size = (4,3))
print("A: \n", A)
# 7
R = np.sum(A, axis=1, keepdims=True)
C = np.mean(A, axis=0, keepdims=True)
print("R: \n", R, "shape: ", R.shape)
print("C: \n", C, "shape: ", C.shape)

A: 
 [[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]]
R: 
 [[ 8]
 [19]
 [10]
 [17]] shape:  (4, 1)
C: 
 [[3.75 4.75 5.  ]] shape:  (1, 3)


Task 8:

Now you have a matrix of shape ($N$,3) with each row $i$ being the coordinates of particle $i$. The aim is to compute the distance matrix that is, a matrix of shape ($N$,$N$) with ($i$,$j$) element being the distance between $i^{th}$ and $j^{th}$ particles.

In [ ]:
# hint for 1 D coordinates
np.random.seed(0)
A = np.random.rand(10)
print(A)

D = A[np.newaxis,:] - A[:,np.newaxis]
D = np.abs(D)
D

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]


array([[0.        , 0.16637586, 0.05394987, 0.00393032, 0.1251587 ,
        0.09708061, 0.11122629, 0.3429595 , 0.41484926, 0.16537199],
       [0.16637586, 0.        , 0.11242599, 0.17030618, 0.29153457,
        0.06929525, 0.27760216, 0.17658363, 0.24847339, 0.33174785],
       [0.05394987, 0.11242599, 0.        , 0.05788019, 0.17910858,
        0.04313074, 0.16517616, 0.28900962, 0.36089938, 0.21932186],
       [0.00393032, 0.17030618, 0.05788019, 0.        , 0.12122838,
        0.10101093, 0.10729597, 0.34688982, 0.41877958, 0.16144166],
       [0.1251587 , 0.29153457, 0.17910858, 0.12122838, 0.        ,
        0.22223931, 0.01393241, 0.4681182 , 0.54000796, 0.04021328],
       [0.09708061, 0.06929525, 0.04313074, 0.10101093, 0.22223931,
        0.        , 0.2083069 , 0.24587889, 0.31776865, 0.26245259],
       [0.11122629, 0.27760216, 0.16517616, 0.10729597, 0.01393241,
        0.2083069 , 0.        , 0.45418579, 0.52607555, 0.05414569],
       [0.3429595 , 0.17658363, 0.2890096

In [ ]:
np.random.seed(0)
positions = np.random.rand(10, 3)*1e11

# 8
x = positions[:, 0]
y = positions[:, 1]
z = positions[:, 2]
diff_x = x[:, np.newaxis] - x[np.newaxis, :]
diff_y = y[:, np.newaxis] - y[np.newaxis, :]
diff_z = z[:, np.newaxis] - z[np.newaxis, :]
dist = np.sqrt(diff_x**2 + diff_y**2 + diff_z**2)
dist

array([[0.00000000e+00, 2.94733968e+10, 4.16894991e+10, 1.96626934e+10,
        5.72166929e+10, 8.65431077e+10, 4.66728373e+10, 3.98299002e+10,
        6.34103186e+10, 4.79024444e+10],
       [2.94733968e+10, 0.00000000e+00, 5.75868031e+10, 4.18602344e+10,
        7.63507592e+10, 6.38095641e+10, 6.03619792e+10, 2.90195223e+10,
        6.93767534e+10, 4.72164080e+10],
       [4.16894991e+10, 5.75868031e+10, 0.00000000e+00, 4.49404524e+10,
        9.02743368e+10, 9.48472677e+10, 3.41591592e+10, 5.91121281e+10,
        9.15585991e+10, 8.33893294e+10],
       [1.96626934e+10, 4.18602344e+10, 4.49404524e+10, 0.00000000e+00,
        5.11502322e+10, 8.80495462e+10, 6.03473399e+10, 5.87539503e+10,
        4.91935359e+10, 6.33134115e+10],
       [5.72166929e+10, 7.63507592e+10, 9.02743368e+10, 5.11502322e+10,
        0.00000000e+00, 1.27710576e+11, 9.33242932e+10, 8.78748549e+10,
        5.37711367e+10, 6.50336340e+10],
       [8.65431077e+10, 6.38095641e+10, 9.48472677e+10, 8.80495462e+10,
   

Task 9:

Using the distance matrix computed above, compute the gravitational potential energy of the system as

$$U = -\sum_{i \neq j}^{N} \frac{Gm_im_j}{r_{ij}}$$

Take the masses to be 1 and $G = 1$.

In [ ]:
# 9
func = np.vectorize(lambda x: -1e15/x if x else 0) # if not scaled up by 1e15 before, values get approximiated to 0
dist_up = np.triu(dist, k=1) # upper triangular matrix above main diagonal
U = np.sum(func(dist_up) / 1e15)
U

-7.889729999999999e-10

Task 10:

Do tasks 8 and 9 using torch.

In [ ]:
positions = torch.tensor(positions, device = 'cuda', requires_grad = False)

# 10
x = positions[:, 0]
y = positions[:, 1]
z = positions[:, 2]


diff_x = x[:, None] - x[None, :]
diff_y = y[:, None] - y[None, :]
diff_z = z[:, None] - z[None, :]
# Task 8

dist = torch.sqrt(diff_x**2 + diff_y**2 + diff_z**2)

# Task 9
func = lambda x: torch.where(x != 0, -1e15/x, 0)

dist_up = torch.triu(dist, diagonal=1) # upper triangular matrix above main diagonal


U = torch.sum(func(dist_up) / 1e15)
U

tensor(-7.8900e-10, device='cuda:0', dtype=torch.float64)

Task 11:

What to do if you need to check for some condition? You have an array $A$, replace all the elements less than zero with zero.

In [ ]:
# hints

A = np.array([0,1,2,3,4])
print(A[[1,4]])
print(A[[True, False, False, True, True]])

[1 4]
[0 3 4]


In [ ]:
# 11
np.random.seed(0)
A = np.random.uniform(low=-1, high=1, size=(10,))
print(A)
A[A < 0] = 0
A

[ 0.09762701  0.43037873  0.20552675  0.08976637 -0.1526904   0.29178823
 -0.12482558  0.783546    0.92732552 -0.23311696]


array([0.09762701, 0.43037873, 0.20552675, 0.08976637, 0.        ,
       0.29178823, 0.        , 0.783546  , 0.92732552, 0.        ])

This is the essence of vectorised operations, we can do more complex stuff but lets keep some of it for later.... Before leaving this section, please try to see equivalent functionalites in pytorch as well.

Pandas:

Pandas mostly is used to load, manipulate and store data. In many cases data is stored in '.csv' format. In this format, the data is stored as an array with each row on a different line and each element of a row separated by ','.

Now do the following tasks,

In [ ]:
array = np.random.rand(100,5)

# store the array in a csv file named numpy.csv use only numpy for this.
np.savetxt("numpy.csv", array, delimiter=",", fmt="%.3f", comments="")
# store the array in a csv file named pandas.csv. This csv must also have a header. Column i must have heading 'column i'.
df = pd.DataFrame(array)
df.to_csv("pandas.csv", index=False, header=["column 1", "column 2", "column 3", "column 4", "column 5"])

In [ ]:
# load the data stored in pandas.csv
df = pd.read_csv("pandas.csv")
print(df.head(3))
print("--------------------------------------------------------------")
# convert the pandas dataframe to numpy array
data = df.to_numpy()
print(data[:3])
print("--------------------------------------------------------------")
# add 1 to all the elements of the numpy array
data = data + 1
print(data[:3])
# store the array to pandas_1.csv. This csv must also have a header. Column i must have heading 'column i'.
df = pd.DataFrame(data)
df.to_csv("pandas_1.csv", index=False, header=["column 1", "column 2", "column 3", "column 4", "column 5"])

   column 1  column 2  column 3  column 4  column 5
0  0.791725  0.528895  0.568045  0.925597  0.071036
1  0.087129  0.020218  0.832620  0.778157  0.870012
2  0.978618  0.799159  0.461479  0.780529  0.118274
--------------------------------------------------------------
[[0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]]
--------------------------------------------------------------
[[1.79172504 1.52889492 1.56804456 1.92559664 1.07103606]
 [1.0871293  1.0202184  1.83261985 1.77815675 1.87001215]
 [1.97861834 1.79915856 1.46147936 1.78052918 1.11827443]]


Task 12:
    This is just to brush up/learn the basics of matplotlib.
Make an animation of a particle moving in a circle with radius 1. The particle should start at (1,0) and move in the anticlockwise direction. The animation should be for 10 seconds. The particle should move with a constant speed. The animation should be in 2D.

bonus: You can also try making it in 3D, change it into an ellipse etc.

In [ ]:
import matplotlib.animation as animation
from IPython.display import HTML

fig, ax = plt.subplots(figsize=(6, 6))

ax.set_xlim(-1.5, 1.5)
ax.set_ylim(-1.5, 1.5)
ax.set_title("Circle Animation")
ax.set_xlabel("X")
ax.set_ylabel("Y")

theta = np.linspace(0, 2 * np.pi, 100)  # 100 points around the circle
circle_x = np.cos(theta)
circle_y = np.sin(theta)
ax.plot(circle_x, circle_y, linestyle="--", color="gray", alpha=0.5, label="Circle Path")  # Dotted circle

# Plot setup
dot, = ax.plot([], [], "ro")  # Red dot

fps = 30
duration = 10
frames = fps * duration

# Angles for smooth motion
angles = np.linspace(0, 2 * np.pi, frames)

# Initialization function
def init():
    dot.set_data([], [])
    return dot,

# Animation function
def animate(frame):
    x = np.cos(angles[frame])
    y = np.sin(angles[frame])
    dot.set_data(x, y)
    return dot,

anim = animation.FuncAnimation(fig, animate, init_func=init, frames=frames, interval=1000 / fps, blit=True)
anim.save("circle_2D_smooth.gif", writer="pillow", fps=fps)

HTML(anim.to_html5_video())

<IPython.core.display.Javascript object>

<ipython-input-9-7ae52dbf6772>:36: MatplotlibDeprecationWarning: Setting data with a non sequence type is deprecated since 3.7 and will be remove two minor releases later
  dot.set_data(x, y)
<ipython-input-9-7ae52dbf6772>:36: MatplotlibDeprecationWarning: Setting data with a non sequence type is deprecated since 3.7 and will be remove two minor releases later
  dot.set_data(x, y)


In [ ]:
fig, ax = plt.subplots(figsize=(6, 6))

ax.set_xlim(-2, 2)
ax.set_ylim(-1.5, 1.5)
ax.set_title("Ellipse Animation")
ax.set_xlabel("X")
ax.set_ylabel("Y")

theta = np.linspace(0, 2 * np.pi, 100)  # 100 points around the circle
ell_x = np.cos(theta) * 1.5
ell_y = np.sin(theta)
ax.plot(ell_x, ell_y, linestyle="--", color="gray", alpha=0.5, label="Circle Path")  # Dotted ellipse

# Plot setup
dot, = ax.plot([], [], "bo")

fps = 30
duration = 10
frames = fps * duration

# Angles for smooth motion
angles = np.linspace(0, 2 * np.pi, frames)

# Initialization function
def init():
    dot.set_data([], [])
    return dot,

# Animation function
def animate(frame):
    x = np.cos(angles[frame]) * 1.5
    y = np.sin(angles[frame])
    dot.set_data(x, y)
    return dot,

anim = animation.FuncAnimation(fig, animate, init_func=init, frames=frames, interval=1000 / fps, blit=True)
anim.save("ellipse_2D_smooth.gif", writer="pillow", fps=fps)

HTML(anim.to_html5_video())

<IPython.core.display.Javascript object>

<ipython-input-10-9ab225cf91cb>:33: MatplotlibDeprecationWarning: Setting data with a non sequence type is deprecated since 3.7 and will be remove two minor releases later
  dot.set_data(x, y)
<ipython-input-10-9ab225cf91cb>:33: MatplotlibDeprecationWarning: Setting data with a non sequence type is deprecated since 3.7 and will be remove two minor releases later
  dot.set_data(x, y)
